issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: blazor-dev
    name: "Blazor Dev"
    secret: blazor-secret
    redirectURIs:
      - "http://localhost:5191/signin-oidc"
      - "https://localhost:7200/signin-oidc"
    postLogoutRedirectURIs:
      - "http://localhost:5191/signout-callback-oidc"
      - "https://localhost:7200/signout-callback-oidc"

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    username: "admin"
    userID: "admin-1"
    # bcrypt hash of "password"
    hash: "$2y$10$da3sPloOzJxlkpE420AoI.HUCVf4U6GHg7NtoJwOu6umz964kLY6a"